version: '{build}'
skip_tags: true
image: Visual Studio 2022
configuration: Release

build_script:
- ps: ./Build.ps1

test: false
artifacts:
- path: artifacts/Serilog.*.nupkg
# deploy:
# - provider: NuGet
#   api_key:
#     secure: rbdBqxBpLt4MkB+mrDOYNDOd8aVZ1zMkysaVNAXNKnC41FYifzX3l9LM8DCrUWU5
#   skip_symbols: true
#   on:
#     branch: /^(master|dev)$/
# - provider: GitHub
#   auth_token:
#     secure: p4LpVhBKxGS5WqucHxFQ5c7C8cP74kbNB0Z8k9Oxx/PMaDQ1+ibmoexNqVU5ZlmX
#   artifact: /Serilog.*\.nupkg/
#   tag: v$(appveyor_build_version)
#   on:
#     branch: master
